---
collections:
  - name: community.general
    version: 5.0.1
  - name: community.sops
    version: 1.2.2
  - name: ansible.posix
    version: 1.4.0
  - name: devsec.hardening
    version: 7.14.1
roles:
  - src: xanmanning.k3s
    version: v3.1.2
